title: Jiyun Cho # your name (or website title) here
logo: "/images/IMG_0185.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>
  <b>AI / ML Data Scientist @ NYU </b>
  <br>Passionate about data and its impact on our society.
  I specialize in Data Science, using analysis and machine learning to uncover meaningful insights and drive informed decision-making. <br><br>
  <a href="https://www.linkedin.com/in/jiyun-c-b69968253/">View My LinkedIn Profile</a> 
  <!-- - a href="https://github.com/jiyun2025">View My GitHub Profile</a> -->
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
